name: Trigger Regression Tests

on:
  workflow_dispatch:

jobs:
  release:
    uses: bactions/workflows/.github/workflows/release-go-server.yml@norelease
    with:
      ref: ${{ github.ref }}
      version: ${{ github.run_id }}_${{ github.run_attempt }}
      os: linux
      cgo_enabled: true
      release_binaries: false
      docker_org: wregulski
      docker_image_name: spv-wallet
      release_create: false
    secrets:
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

  trigger_regression_tests:
    needs: release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Trigger Regression Tests
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          RUN_ID=${{ github.run_id }}_${{ github.run_attempt }}
          IMAGE_TAG=${{ needs.release.outputs.imageVersion }}
          curl -X POST -H "Accept: application/vnd.github+json" \
               -H "Authorization: token $GH_TOKEN" \
               https://api.github.com/repos/4chain-ag/spv-wallet-regression/dispatches \
               -d '{"event_type":"regression_tests","client_payload":{"image_tag":"'"${IMAGE_TAG}"'", "run_id":"'"${RUN_ID}"'"}}'
